package exception;

public class exception2 {
	public static void exception() {
 
	throw new ArithmeticException("divide by 0");
	}
	public static void main(String[] args) {
	exception();
	}

}
